### ISSUE TITLE
space.getEnvironment is not a function error

### ISSUE THREAD

**Issue by amandasage** [lotas/contentful-graph#18]
Hey lotas,

I'm having a Contentful user running into the attached error after following the instructions on the plugin page
space.GetEnvironment is not a function.

Thank you!

Update: Was able to resolve

**Comment by lotas** [comment]
Oops. Late to the party :) Good!

**Comment by x-stefan** [comment]
BUT HOW? 
Please share your solution the next time, because I have the same issue and need to solve it 😉

**Comment by lotas** [comment]
> BUT HOW?
> Please share your solution the next time, because I have the same issue and need to solve it 😉

My guess is that credentials are incorrect. 
Depending on the type of keys you have (management or distribution), can you please debug `import-distribution.js` and `import-management.js` to see if `client.getSpace(spaceId)` returns anything valid and `spaceId` is set properly?

**Comment by x-stefan** [comment]
I just figured out it works with the CMA Token, but doesn't seem to work with my CDA Token.

With the CDA Token, `client.getSpace()` returns me an object like this:

```js
{
  sys: { type: 'Space', id: 'XXX' },
  name: 'XXX',
  locales: [ { code: 'de', default: true, name: 'German', fallbackCode: null } ]
}
```

**Comment by lotas** [comment]
huh! that might be a problem indeed. Checked [documentation](https://contentful.github.io/contentful.js/contentful/7.14.8/Entities.html#.Space), it doesn't have `getEnvironment()` function anymore.

For now I would recommend using CMA way.. will check if this is something that can be fixed, or CDA is no longer suitable for this kind of metadata fetching

**Comment by Swissbite** [comment]
#28 fixes this issue

**Comment by lotas** [comment]
@Swissbite fixed this issue, PR merged. Thanks!
