### ISSUE TITLE
Make it an npm module

### ISSUE THREAD

**Issue by stefanjudis** [lotas/contentful-graph#2]
Heyo. 👋 

I'm really digging this module. Do you have plans to make it a proper npm module?

**Comment by lotas** [comment]
Hey @stefanjudis 
I didn't think about this to be honest, but I agree that this makes sense. Will do.
Thnx!

**Comment by stefanjudis** [comment]
Let me know how it goes. ;) 

I think this can be a really valuable tool and I'd like to feature it in our "Tools, Libraries and Utilities" in our [developer portal](https://www.contentful.com/developers/) when running smoothly and is a proper module.

**Comment by lotas** [comment]
Hey @stefanjudis @floelhoeffel
Thanks to your comments and guidance I finally managed to publish it 🎉 

It can be used in multiple ways now:

CLI:  `npx contentful-graph`  (env variables must be set)

`CONTENTFUL_SPACE_ID=123 CONTENTFUL_MANAGEMENT_TOKEN=token npx contentful-graph`

Or programmatically by importing `convertApi` 

Thanks!

**Comment by stefanjudis** [comment]
That's so cool! Thanks for doing that. I'll play around with it again next week.. 🎉

**Comment by lotas** [comment]
Thank you! Have fun :)
