### ISSUE TITLE
RichText link does not reflect all configurations #19

### ISSUE THREAD

**Issue by Swissbite** [lotas/contentful-graph#23]
The fix introduced in PR #21 for issue #19 does not reflect all possible states.

Missing / not working:

- If there are no restrictions, it just fails / breaks
- If there are **no** links / assets to entries allowed by disabling linking to any asset / entry, it will assume that **everything** is allowed

**Comment by Swissbite** [comment]
Fix for that is in progress :-)

**Comment by lotas** [comment]
Cool! Thanks!
