### ISSUE TITLE
Update dependencies to "latest" version

### ISSUE THREAD

**Issue by Swissbite** [lotas/contentful-graph#25]
Almost all dependencies are outdated.

I would also upgrade to the supported version of Node.JS.

Supported minimal version of node would be 10.*
Supported minimal version of npm would be 6.14.*

**Comment by lotas** [comment]
Danke sehr!

**Comment by Swissbite** [comment]
You're welcome :-) It's a tool I'm currently using, so I can help to improve it ;-)

**Comment by lotas** [comment]
That's really awesome, because I'm not using contentful at the moment, and don't have always time to check what's happening there :-/
